Repository programer653/SOEN341-teamproject4, pull requests merged in 2022-03, with the labels that each got.

#24 Add to cart increment1
  amazon-clone/src/Checkout.js
  amazon-clone/src/CheckoutProduct.css
  amazon-clone/src/CheckoutProduct.js
  amazon-clone/src/Header.js
  amazon-clone/src/Product.js
  amazon-clone/src/Subtotal.js
  amazon-clone/src/reducer.js
Labels: 3 pt, Medium Priority, Front-end, Back-end, Pull request

#25 Remove item checkout
  amazon-clone/src/Checkout.js
  amazon-clone/src/CheckoutProduct.css
  amazon-clone/src/CheckoutProduct.js
  amazon-clone/src/reducer.js
Labels: 1 pt, Low Risk, Task, Pull request

#34 About us page adding to the main
  amazon-clone/src/AboutUs.css
  amazon-clone/src/AboutUs.js
  amazon-clone/src/App.js
  amazon-clone/src/Footer.js
  amazon-clone/src/images/aminata.jpg
  amazon-clone/src/images/asha.jpg
  amazon-clone/src/images/pavi.jpg
Labels: 0 pt, Low Priority, Low Risk, Pull request

#36 Promotion page
  amazon-clone/src/App.js
  amazon-clone/src/NavigationBar.js
  amazon-clone/src/Product.css
  amazon-clone/src/Product.js
  amazon-clone/src/Promotion.css
  amazon-clone/src/Promotion.js
Labels: 1 pt, Low Priority, Low Risk, Front-end, Back-end, Task

#41 Login Page Update
  .DS_Store
  amazon-clone/.firebaserc
  amazon-clone/database.rules.json
  amazon-clone/firebase.json
  amazon-clone/firestore.indexes.json
  amazon-clone/firestore.rules
  amazon-clone/functions/.gitignore
  amazon-clone/functions/index.js
  amazon-clone/functions/package-lock.json
  amazon-clone/functions/package.json
  amazon-clone/package-lock.json
  amazon-clone/package.json
  amazon-clone/remoteconfig.template.json
  amazon-clone/src/Admin.css
  amazon-clone/src/Admin.js
  amazon-clone/src/App.css
  amazon-clone/src/App.js
  amazon-clone/src/Config/Config.js
  amazon-clone/src/DisplayProduct.css
  amazon-clone/src/DisplayProduct.js
  amazon-clone/src/Header.js
  amazon-clone/src/Home.js
  amazon-clone/src/Login.css
  amazon-clone/src/Login.js
  amazon-clone/src/NavigationBar.js
  amazon-clone/src/Payment.css
  amazon-clone/src/Payment.js
  amazon-clone/src/ProductDetails.js
  amazon-clone/src/Subtotal.js
  amazon-clone/src/reducer.js
  amazon-clone/storage.rules
  node_modules/protobufjs/cli/node_modules/tmp/CHANGELOG.md
  node_modules/protobufjs/cli/node_modules/tmp/LICENSE
  node_modules/protobufjs/cli/node_modules/tmp/README.md
  node_modules/protobufjs/cli/node_modules/tmp/lib/tmp.js
  node_modules/protobufjs/cli/node_modules/tmp/package.json
  node_modules/tmp/CHANGELOG.md
  node_modules/tmp/LICENSE
  node_modules/tmp/README.md
  node_modules/tmp/lib/tmp.js
  node_modules/tmp/package.json
Labels: Front-end, Back-end, Pull request

#42 Merging the Featured Products in the home page into the Filtering Product Branch
  .DS_Store
  amazon-clone/package-lock.json
  amazon-clone/package.json
  amazon-clone/public/Featured_img/ipad.jpeg
  amazon-clone/public/Featured_img/iphone.jpeg
  amazon-clone/public/Featured_img/nike.jpeg
  amazon-clone/public/Featured_img/teddy.jpeg
  amazon-clone/src/AnimationPage.js
  amazon-clone/src/App.js
  amazon-clone/src/BtnSlider.js
  amazon-clone/src/FeaturedProducts.css
  amazon-clone/src/FeaturedProducts.js
  amazon-clone/src/Promotion.css
  amazon-clone/src/dataSlider.js
  amazon-clone/src/filteringProduct.css
  amazon-clone/src/filteringProduct.js
  amazon-clone/src/images/left-arrow.png
  amazon-clone/src/images/right-arrow.png
Labels: Low Priority, Low Risk, Front-end, Task, Pull request
